#include QMK_KEYBOARD_H

enum layers {
_QWERTY,
_LOWER
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [_QWERTY] = LAYOUT (
      KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_BSPC, KC_EQUAL, KC_MINUS, KC_0, KC_9, KC_8, KC_7,
      KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_QUOTE, KC_LBRACKET, KC_P, KC_O, KC_I, KC_U, KC_Y,
      KC_CAPSLOCK, KC_A, KC_S, KC_D, KC_F, KC_G, KC_ENTER, KC_SCOLON, KC_L, KC_K, KC_J, KC_H,
      KC_LSHIFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_RSHIFT, KC_SLASH, KC_DOT, KC_COMMA, KC_M, KC_N,
      KC_LCTRL, KC_LALT, KC_LGUI, KC_SPACE, MO(_LOWER), KC_LGUI, KC_TRNS, KC_SPACE
  ),
  [_LOWER] = LAYOUT (
    KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_BSPC, KC_F12, KC_F11, KC_F10, KC_F9, KC_F8, KC_F7,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_UP, KC_TRNS, KC_TRNS, KC_TRNS, KC_RBRACKET, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_LEFT, KC_DOWN, KC_RIGHT, KC_TRNS, KC_TRNS, KC_SCOLON, KC_TRNS, KC_TRNS, KC_AUDIO_VOL_UP, KC_AUDIO_VOL_DOWN,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MEDIA_PREV_TRACK, KC_MEDIA_PREV_TRACK,
    KC_TRNS, KC_TRNS, KC_LGUI, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
  )
};
